[package]
name = "black_hat_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sha1_cracker"
version = "0.1.0"
path = "src/bin/sha1_cracker.rs"

[dependencies]
hex = "0.4.3"
sha1 = "0.10.5"
